@CadastroProdutos_HostAddress = http://localhost:5197

GET {{CadastroProdutos_HostAddress}}/weatherforecast/
Accept: application/json

###

POST http://localhost:5197/produtos
Content-Type: application/json

{
  "nome": "Monitor",
  "preco": 500.00,
  "estoque": 10
}
